# D9
d9:
  logging_level: "info"

# X-Plane Connection Settings
xplane_api:
  web_api_http_url:       "http://127.0.0.1:8086/api/v2"
  web_api_websocket_url:  "ws://127.0.0.1:8086/api/v2"

# ATC Settings
atc:
  message_buffer_size:    40
  listen_all_frequencies: true
  strict_flightplan_matching: false
  airlines_file:     "resources/airlines.json"
  atc_data_file:     "/home/dmorris/decimal-niner/X-Plane/atc.dat"
  atc_regions_file:  "/home/dmorris/decimal-niner/X-Plane/atc_regions.dat"
  atc_holds_file:    "/home/dmorris/decimal-niner/X-Plane/earth_hold.dat"
  atc_nav_data_file: "/home/dmorris/decimal-niner/X-Plane/earth_nav.dat"
  atc_fixes_file:    "/home/dmorris/decimal-niner/X-Plane/earth_fix.dat"
  airports_cifp_dir: "/home/dmorris/decimal-niner/X-Plane/CIFP"
  #airports_data_file:   "/home/dmorris/decimal-niner/X-Plane/apt.min.dat"  # minimal for development speed
  airports_data_file:       "/home/dmorris/decimal-niner/X-Plane/apt.dat"   # full file - slow 
  voices:
    phrases_file:       "resources/phrases.json"
    unicom_phrases_file: "resources/phrases_unicom.json"
    sox:
      application: "/usr/bin/play"
    piper:
      application:        "/home/dmorris/.local/bin/piper"
      voice_directory:    "/home/dmorris/piper-voices"
      speakers:
        - voice_file: "en_GB-vctk-medium.onnx"
          ids: [3,7,9,13,14,19,20,22,27,28,29,30,31,36,38,39,46,48,50,55,57,58,60,62,63,69,70,71,72,75,76,78,79,92,94,96,98,99,102,104,107]
    handoff_valediction_factor: 5  
    say_again_factor: 30
    comms_country_code_default: "GB"
trafficglobal:
  plugin_directory: "/home/dmorris/decimal-niner/X-Plane/Resources/plugins/Traffic Global"
  #plugin_directory: "/home/dmorris/decimal-niner/X-Plane"